### PR TITLE
C++ development mode

### PR DESCRIPTION
**Pull request by krlmlr**
- More Makevars entries
- Expand unfinished paragraph

### CODE REVIEW

**Comment by krlmlr** [comment]
I assign the copyright of this contribution to Hadley Wickham.

**Comment by jennybc** [comment]
Thanks! This has been here awhile ... I'm clearing things out in order to make a "release" to freeze the 1st edition and begin work on the 2nd. Does this need any sort of refresh?

cc @jimhester

**Comment by krlmlr** [comment]
Seems that `load_all()` has improved a lot, I'm not sure the suggestion to use "Build & Reload" is still valid.

**Comment by jimhester** [comment]
The described behavior of `load_all()` is not correct, it does recompile both header and object files as necessary. It can still be problematic to use `load_all()` when developing on windows due to OS locking of the shared library, but on POSIX machines it works well.

I also don't really agree with the other Makevars changes. `MAKEFLAGS` I feel is better set in your shell environment and if you want to turn off optimizations I think it is much more clear to do so in `CFLAGS`, `CXXFLAGS` etc. than using the `LTO` hack. If the `LTO` setting remains it would need much more descriptive text on why it works and why it is not an issue to override any existing LTO settings etc. Also generally I would recommend `-Og` rather than `-O0` when doing development <https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html>

**Comment by jennybc** [comment]
I'm going to convert this to an issue to remind us to revisit these recommendations in the 2nd edition. Sounds like this is not a no-brainer correction type of PR that should clearly be part of the 1st edition "release".

**Pull request closed without merging**
