### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by miguelmorin**
Hello Hadley, I am reading the book from cover to cover and making edits to GitHub as I find typos. Please find here two typos on one chapter.

I assign the copyright of this contribution to Hadley Wickham.

### CODE REVIEW

**Comment by jennybc** [comment]
I'm not able to see what needs to be fixed here.

**Comment by miguelmorin** [comment]
Hi Jenny, the two changes are:

(1) Line 28 had a new line in the middle of a sentence:
Pick a unique name you can easily Google. This makes it easy for potential users to [new line]  find your package (and associated resources) and for you to see who's using it.

(2) Lines 147 - 150: the two figures side by side overflowed in the PDF rendering, so I split them into 2 chunks and they appear one below the other.

**Comment by batpigandme** [comment]
I do see what you're saying for the extraneous line-break (jenny, see below). 
image

As for the figures, I don't know that they're worth changing as they render fine in the online version/look strange stacked, and are likely to change entirely for the second edition.

**Comment by jennybc** [comment]
Aha! OK I've made the whitespace fix myself and linked here and credited @miguelmorin. I couldn't reopen this because the associated fork is gone. Plus I don't think I could merge the change re: chunks and figures anyway.

Thanks!

**Pull request closed without merging**
