### PR TITLE
Line 581 is incomplete.

### PR DESCRIPTION
**Pull request by sn248**
The line starting with, "If you have C objects ..., then it's ..' - this line is incomplete (noted here by _incomplete_

### CODE REVIEW

**Comment by sn248** [comment]
Line 581 looks incomplete.

**Comment by sn248** [comment]
I assign the copyright of this contribution to Hadley Wickham.

**Comment by jennybc** [comment]
cc @jimhester 

Is it obvious how this sentence/paragraph should end? 🤔

**Comment by jimhester** [comment]
No, I don't think it is obvious

**Comment by jimhester** [comment]
There is an example as part of https://github.com/hadley/r-pkgs/pull/352, but maybe it would be better to have @hadley finish it, or rework the sentence / paragraph entirely.

**Comment by jennybc** [comment]
I've asked @hadley to finish the sentence in #456.

Thanks @sn248 for catching it.

**Comment by sn248** [comment]
Thanks to @jennybc, @jimhester and @hadley for looking at this. The book is a wonderful resource!

**Pull request closed without merging**
