### PR TITLE
Change license sticky versioning example from = to ==

### PR DESCRIPTION
**Pull request by Skenvy**
Missing one = in the example Apache license.

### CODE REVIEW

**Comment by Skenvy** [comment]
Fixes #844

**Comment by Skenvy** [comment]
It's 8 years old now, is https://github.com/hadley/r-pkgs/blob/73ed0cd0195d14de3b697a467dbc5a494b10ca1a/CONTRIBUTING.md still relevant?

**Comment by Skenvy** [comment]
Discovered as https://github.com/Skenvy/Collatz/blob/1836f0a9622e87329c22751ca1ed0194745f1cf2/R/DESCRIPTION#L3 was generating a warning in CMD check, but changing to two = removed the warning.

**Comment by jennybc** [comment]
Searching the DESCRIPTION files of CRAN packages using the Apache license, I see (at least) two forms:

```
License: Apache License 2.0
License: Apache License (== 2.0)
```

We appear to be trying to model the second form, so I'm merging this. Thanks!

**Pull request merged**
